### ISSUE TITLE
Companion manager macro

### ISSUE THREAD

**Issue by lucaspicerni** [p4535992/foundryvtt-automated-evocations-variant#1]
Please include a macro in the module to open the Companion Manager window, so that each user can just use the macro and choose from the list of their companions what they want to conjure!

**Comment by p4535992** [comment]
There is already this function, check out the [API documentation](https://github.com/p4535992/automated-evocations-variant#api).
For your use case should be fine this:
`game.modules.get('automated-evocations-variant').api.invokeEvocationsVariantManager('ID OR NAME OF THE TOKEN ON THE CANVAS')`

if you have some suggestion let me know it.

**Comment by lucaspicerni** [comment]
I read the API documentation and somehow managed to do it. But is there any way to make the macro invoke the manager using an actor's id rather than a token?

**Comment by p4535992** [comment]
Added a macro for make the invocation from the actor reference:
`game.modules.get('automated-evocations-variant').api.invokeEvocationsVariantManagerFromActor('Zruggig Widebrain')`

**Comment by lucaspicerni** [comment]
I'm receiving this error:

![image](https://user-images.githubusercontent.com/95550238/171965022-61dc432e-c21e-4535-916e-bf4064f5bf73.png)

**Comment by p4535992** [comment]
Sorry made a mistake try out 1.5.14

**Comment by p4535992** [comment]
@lucaspicerni sorry to bother  can i close this ticket ?

**Comment by lucaspicerni** [comment]
Sorry for the delayed response. Sure, thank you!

**Comment by p4535992** [comment]
great!!
