### ISSUE TITLE
[BUG] Error adding actor to evocation list

### ISSUE THREAD

**Issue by lucaspicerni** [p4535992/foundryvtt-automated-evocations-variant#10]
**Module Version:** 1.6.13

**Describe the bug**: Hello! After updating the module, I am getting the following error, when I try to drag a new actor into another actor's evocations, and nothing happens:

**Screenshots:**
![image](https://user-images.githubusercontent.com/95550238/220471548-805b193c-e396-4b00-8cb7-8a23bd8b312e.png)

**To Reproduce:**
1. Create world
2. Enable modules
3. Try to add actor to another actor's summon list by dragging it

**Browser:** Chrome
**Foundry Version:** 10.291
**Game System:** Both D&D 2.1.5 and Chronicles of Darkness 0.11.1
**Additional context**: Using libwrapper 1.12.12.0, socketlib 1.0.12, sequencer 2.411 and warpgate 1.15.4

**Comment by p4535992** [comment]
Try out 1.6.14

**Comment by lucaspicerni** [comment]
The issue has been resolved, but now I'm getting the following error when summoning an actor:

![image](https://user-images.githubusercontent.com/95550238/221424930-900bca1a-6fbf-4341-86e7-b514e0553742.png)

Evocation window minimizes, animation happens, but no token is created. Consequently, the window remains closed.

**Comment by p4535992** [comment]
Try out 1.6.15

**Comment by lucaspicerni** [comment]
Working normally, thank you!
