### ISSUE TITLE
[BUG] Errors while using automation

### ISSUE THREAD

**Issue by lucaspicerni** [p4535992/foundryvtt-automated-evocations-variant#11]
**Describe the bug**
Hello! I'm having trouble using the module's automation. Whenever a spell registered with automation (either through the console or through the module's menu) is rolled, the invocation menu does not appear and I receive this error in the console:

![image](https://user-images.githubusercontent.com/95550238/225205771-13dbb370-eb75-4a60-b30f-a29716891ba5.png)
![image](https://user-images.githubusercontent.com/95550238/225205791-6586a880-ab5b-422e-b863-98421e4c7d10.png)

**Module Version:** 1.6.15
**Browser:** Chrome 
**Foundry Version:** 10.291
**Game System:** D&D 5e

**Comment by p4535992** [comment]
tried to fix on 1.6.16
