### ISSUE TITLE
Errors when using the custom bindings menu

### ISSUE THREAD

**Issue by lucaspicerni** [p4535992/foundryvtt-automated-evocations-variant#13]
Hello! When trying to use the "Configure Custom Binding" module menu, the skill/spell name is not saved, and this error is thrown in the console:

![image](https://user-images.githubusercontent.com/95550238/229614042-aa348f44-0b62-4c37-9859-9287c8e790d3.png)

It is also not possible to register custom spells through the console, because of [this bug](https://github.com/p4535992/foundryvtt-automated-evocations-variant/issues/11).

**Browser:** Chrome
**Module Version:** 1.6.15
**Foundry Version:** 10.291
**Game System:** D&D 5e 2.1.5

**Comment by p4535992** [comment]
tried to fix on 1.6.16

**Comment by DanielTheBard** [comment]
I am also having this same problem still. I am on version 1.6.16
